"""gmail connection duration and failure tracking

Revision ID: 823120af707f
Revises: db677a4ee2fb
Create Date: 2026-09-01 20:30:53.979053

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '823120af707f'
down_revision: Union[str, Sequence[str], None] = 'db677a4ee2fb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('gmail_accounts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('connected_at', sa.DateTime(timezone=True), nullable=True))
        batch_op.add_column(sa.Column('duration_hours', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('consecutive_failures', sa.Integer(), server_default='0', nullable=False))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('gmail_accounts', schema=None) as batch_op:
        batch_op.drop_column('consecutive_failures')
        batch_op.drop_column('duration_hours')
        batch_op.drop_column('connected_at')

    # ### end Alembic commands ###
