"""baseline schema

Revision ID: db677a4ee2fb
Revises: 
Create Date: 2026-09-01 19:43:12.811021

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'db677a4ee2fb'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sessions',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('monitoring_active', sa.Boolean(), nullable=False),
    sa.Column('seeded', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('gmail_accounts',
    sa.Column('session_id', sa.String(length=32), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('app_password_enc', sa.Text(), nullable=False),
    sa.Column('connected', sa.Boolean(), nullable=False),
    sa.Column('last_scan_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('seen_ids', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('session_id')
    )
    op.create_table('inbox_items',
    sa.Column('id', sa.String(length=48), nullable=False),
    sa.Column('session_id', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('message_id', sa.String(length=512), nullable=False),
    sa.Column('sender_address', sa.String(length=320), nullable=False),
    sa.Column('display_name', sa.String(length=320), nullable=False),
    sa.Column('subject', sa.Text(), nullable=False),
    sa.Column('recipient', sa.String(length=320), nullable=False),
    sa.Column('date_str', sa.String(length=120), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('urls', sa.JSON(), nullable=False),
    sa.Column('attachments', sa.JSON(), nullable=False),
    sa.Column('spf_status', sa.String(length=16), nullable=False),
    sa.Column('dkim_status', sa.String(length=16), nullable=False),
    sa.Column('dmarc_status', sa.String(length=16), nullable=False),
    sa.Column('analysis', sa.JSON(), nullable=False),
    sa.Column('is_quarantined', sa.Boolean(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('incident_id', sa.String(length=48), nullable=True),
    sa.Column('gmail_web_url', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('inbox_items', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_inbox_items_session_id'), ['session_id'], unique=False)

    op.create_table('incident_reports',
    sa.Column('incident_id', sa.String(length=48), nullable=False),
    sa.Column('session_id', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('incident_id')
    )
    with op.batch_alter_table('incident_reports', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_incident_reports_session_id'), ['session_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('incident_reports', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_incident_reports_session_id'))

    op.drop_table('incident_reports')
    with op.batch_alter_table('inbox_items', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_inbox_items_session_id'))

    op.drop_table('inbox_items')
    op.drop_table('gmail_accounts')
    op.drop_table('sessions')
    # ### end Alembic commands ###
